### ISSUE TITLE
Add more linting rules

### ISSUE THREAD

**Issue by ShirinkinArseny** [vilka27/WebGlDemo#11]
I want to have space after every colon:

`function getOctoModel(gl:WebGLRenderingContext):Model{`

should be replaced with

`function getOctoModel(gl: WebGLRenderingContext): Model{`

Also I wanna to have space after every comma. Now we have:

`return new Model(gl,positions,indices,[1,1,0,1]);`

, but I want to have:

`return new Model(gl, positions, indices, [1, 1, 0, 1]);`

**Comment by vilka27** [comment]
Fixed
